#spring.data.mongodb.uri=mongodb://localhost:27017/journaldb
#spring.data.mongodb.auto-index-creation=true
spring.data.mongodb.uri=mongodb+srv://gaurav472:lucifer472002@cluster0.pfxnloy.mongodb.net/journaldb?retryWrites=true&w=majority
spring.data.mongodb.auto-index-creation=true